name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t docker.pkg.github.com/${{ github.repository }}/main:latest .
          docker buildx stop

      - name: Push Docker Image Tags
        run: |
          docker buildx create --use
          docker buildx imagetools create docker.pkg.github.com/${{ github.repository }}/main:latest
          docker buildx imagetools tag docker.pkg.github.com/${{ github.repository }}/main:latest docker.pkg.github.com/${{ github.repository }}/main:${{ github.sha }}
          docker buildx imagetools push docker.pkg.github.com/${{ github.repository }}/main --all
          docker buildx stop
